Pulling new cAdvisor image from Google.
alliance-genome/agr_ansible_devops pull request #57
Opened 2023-04-24 23:27 UTC by christabone

@oblodgett This is already live on production, I had to restart the monitoring service and pull the cAdvisor image from a new location, otherwise we would have no stats from the server.

Since it's already deployed, I think it's OK to go into master?

2023-04-24 23:30 UTC, oblodgett approved these changes

2023-04-24 23:30 UTC, oblodgett requested changes
Needs to go into release-6.0.0

2023-04-24 23:31 UTC, christabone commented
@oblodgett Even though it's live on `5.4.0`? 

If we redeploy `master` to change anything then the stats would be broken again if the fix is in `release-6.0.0`.

2023-04-25 10:16 UTC, mluypaert approved these changes

2023-05-04 15:01 UTC, closed without merging